### ISSUE TITLE
Failing tests on master

### ISSUE THREAD

**Issue by atwright147** [starlingbank/starling-developer-sdk#52]
Hey,

I am finding that there are currently 4 failing tests on `master`. Is this just on my Win10 machine or is it a mistake in the repo?

```sh
> npm t

> starling-developer-sdk@1.0.3 test
> jest test

 PASS  test/entities/feedItem.spec.js
 PASS  test/entities/accountHolder.spec.js
 FAIL  test/entities/account.spec.js
  ● Account › should download CSV statement for period

    expect(received).toBe(expected) // Object.is equality

    Expected: "Date,Counter Party,Reference,Type,Amount (GBP),Balance (GBP),Spending Category"
    "eceived: "Date,Counter Party,Reference,Type,Amount (GBP),Balance (GBP),Spending Category

      154 |
      155 |         expect(lines).toHaveLength(4)
    > 156 |         expect(lines[0]).toBe('Date,Counter Party,Reference,Type,Amount (GBP),Balance (GBP),Spending Category')
          |                          ^
      157 |         expect(lines[1]).toBe('01/10/2019,An Employer,SALARY,FASTER PAYMENT,1500.00,5500.00,INCOME')
      158 |         expect(lines[2]).toBe('02/10/2019,Landlord,Rent,FASTER PAYMENT,-1000.00,4500.00,PAYMENTS')
      159 |         expect(lines[3]).toBe('')

      at test/entities/account.spec.js:156:26

  ● Account › should download CSV statement for period with optional parameters removed

    expect(received).toBe(expected) // Object.is equality

    Expected: "Date,Counter Party,Reference,Type,Amount (GBP),Balance (GBP),Spending Category"
    "eceived: "Date,Counter Party,Reference,Type,Amount (GBP),Balance (GBP),Spending Category

      172 |
      173 |         expect(lines).toHaveLength(4)
    > 174 |         expect(lines[0]).toBe('Date,Counter Party,Reference,Type,Amount (GBP),Balance (GBP),Spending Category')
          |                          ^
      175 |         expect(lines[1]).toBe('01/10/2019,An Employer,SALARY,FASTER PAYMENT,1500.00,5500.00,INCOME')
      176 |         expect(lines[2]).toBe('02/10/2019,Landlord,Rent,FASTER PAYMENT,-1000.00,4500.00,PAYMENTS')
      177 |         expect(lines[3]).toBe('')

      at test/entities/account.spec.js:174:26

  ● Account › should download CSV statement for range

    expect(received).toBe(expected) // Object.is equality

    Expected: "Date,Counter Party,Reference,Type,Amount (GBP),Balance (GBP),Spending Category"
    "eceived: "Date,Counter Party,Reference,Type,Amount (GBP),Balance (GBP),Spending Category

      190 |
      191 |         expect(lines).toHaveLength(4)
    > 192 |         expect(lines[0]).toBe('Date,Counter Party,Reference,Type,Amount (GBP),Balance (GBP),Spending Category')
          |                          ^
      193 |         expect(lines[1]).toBe('01/10/2019,An Employer,SALARY,FASTER PAYMENT,1500.00,5500.00,INCOME')
      194 |         expect(lines[2]).toBe('02/10/2019,Landlord,Rent,FASTER PAYMENT,-1000.00,4500.00,PAYMENTS')
      195 |         expect(lines[3]).toBe('')

      at test/entities/account.spec.js:192:26

  ● Account › should download CSV statement for range with optional parameters removed

    expect(received).toBe(expected) // Object.is equality

    Expected: "Date,Counter Party,Reference,Type,Amount (GBP),Balance (GBP),Spending Category"
    "eceived: "Date,Counter Party,Reference,Type,Amount (GBP),Balance (GBP),Spending Category

      208 |
      209 |         expect(lines).toHaveLength(4)
    > 210 |         expect(lines[0]).toBe('Date,Counter Party,Reference,Type,Amount (GBP),Balance (GBP),Spending Category')
          |                          ^
      211 |         expect(lines[1]).toBe('01/10/2019,An Employer,SALARY,FASTER PAYMENT,1500.00,5500.00,INCOME')
      212 |         expect(lines[2]).toBe('02/10/2019,Landlord,Rent,FASTER PAYMENT,-1000.00,4500.00,PAYMENTS')
      213 |         expect(lines[3]).toBe('')

      at test/entities/account.spec.js:210:26

 PASS  test/entities/savingsGoals.spec.js
 PASS  test/entities/card.spec.js
 PASS  test/entities/payee.spec.js
 PASS  test/entities/payment.spec.js
 PASS  test/oauth.spec.js
 PASS  test/entities/identity.spec.js
 PASS  test/entities/address.spec.js
 PASS  test/utils/validator.spec.js
 PASS  test/entities/mandate.spec.js
 PASS  test/starling.spec.js

Test Suites: 1 failed, 12 passed, 13 total
Tests:       4 failed, 64 passed, 68 total
Snapshots:   0 total
Time:        6.472 s
Ran all test suites matching /test/i.
```

Thank you for your time :)

**Comment by atwright147** [comment]
Is anybody looking at this?

**Comment by domdomegg** [comment]
Hi @atwright147, apologies for the delay getting back to you. The tests appear to pass in the CI (https://github.com/starlingbank/starling-developer-sdk/runs/1722545869) and on my local machine pulling the latest changes (see screenshot).

![image](https://user-images.githubusercontent.com/4953590/108046919-1904e800-703d-11eb-8083-66e00fe1fd4d.png)

Not sure what the issue could be - what is strange though is your Jest output seems to be a bit off, i.e. `"eceived` instead of `Received`. Might be worth trying to reinstall dependencies (`npm ci` should do the trick) and retry?

**Comment by domdomegg** [comment]
Ah just seen your PR, Windows line-endings look like they explain it. Still odd about the Jest output but 🤷

**Comment by atwright147** [comment]
Are you on Windows, Mac or Linux?

**Comment by domdomegg** [comment]
> Are you on Windows, Mac or Linux?

Generally a mix of Mac and Linux, hence missed the Windows line endings. Thanks again for raising the issue and the PR 🙌

**Comment by atwright147** [comment]
That odd, I found the error on a Mac
